//
//  Assets.h
//  WWDC
//
//  Created by Genady Okrain on 10/1/14.
//  Copyright (c) 2014 Sugar So Studio. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface Assets : NSObject

// Drawing Methods
+ (void)drawLocation;
+ (void)drawAddToCalendar;

@end
